name: Run Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate Github token for Renovate App
        id: token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: sthdev

      - name: Run Renovate
        uses: renovatebot/github-action@3f10d7a25cf0aa7b37519aa771ed9143fcbb5da5 # v41.0.10
        with:
          token: ${{ steps.token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: '["sthdev/renovate-33658"]'
