name: Run Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Renovate
        uses: renovatebot/github-action@531c6786d6cf05ef148c4cfe251745c2c6de442c # v41.0.9
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
